package tk.mybatis.simple.mapper;

import tk.mybatis.simple.model.SysUserWithBLOBs;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Fri Jun 07 14:30:45 CST 2019
     */
    int insert(SysUserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Fri Jun 07 14:30:45 CST 2019
     */
    int insertSelective(SysUserWithBLOBs record);
}